language: r
python:
 - 3.6
 - 3.7
 - 2.7
os:
 - osx
 - linux
dist: xenial
r:
 - devel
 - release
 - oldrel

before_install:
 - chmod +x ./travis/install.sh
 - ./travis/install.sh

matrix:
  exclude:
    - r: devel
      os: osx
