language: r
python:
 - 3.6
 - 3.7
 - 2.7
os:
 - osx
 - linux
dist: xenial
osx_image: xcode9.2
before_install:
    - if [[ "$OSTYPE" == "osx" ]]; then sudo tlmgr install inconsolata; fi

r:
 - devel
 - release
 - oldrel
matrix:
 exclude:
 - os: osx
   r: devel
